jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewer
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = context.github;
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;
            const prNumber = context.payload.number;
            const reviewer = 'tusharupase786';

            await github.pulls.createReviewRequest({
              owner: owner,
              repo: repo,
              pull_number: prNumber,
              reviewers: [reviewer]
            });
